update tenant name separately

diff --git a/.github/workflows/create-hasura-preview-tenant.yml b/.github/workflows/create-hasura-preview-tenant.yml
--- a/.github/workflows/create-hasura-preview-tenant.yml
+++ b/.github/workflows/create-hasura-preview-tenant.yml
@@ -91,6 +91,46 @@ jobs:
           echo "Endpoint: $endpoint"
           echo "endpoint=$endpoint" >> "$GITHUB_OUTPUT"
 
+      # we set the name above, but it doesn't work on Hasura's end, frustratingly
+      - name: Update Tenant name
+        id: update-tenant-name
+        run: |
+          GQL_QUERY=$(cat <<-GQL
+            mutation UpdateTenantName {
+              updateTenant(
+                tenantId: "${{steps.create-tenant.outputs.tenant_id}}}}"
+                name: "${{inputs.tenant-name}}"
+              ) {
+                tenant_id
+              }
+            }
+          GQL
+          )
+
+          REQUEST_PAYLOAD=$(jq -n --arg gqlQuery "$GQL_QUERY" '{ "query": $gqlQuery }')
+
+          # Send the request using curl
+          RESPONSE=$(curl \
+            --fail-with-body \
+            --silent \
+            --show-error \
+            --location \
+            --request POST \
+            --header 'Content-Type: application/json' \
+            --header 'Authorization: pat ${{ secrets.hasura-cloud-access-token }}' \
+            --data "$REQUEST_PAYLOAD" \
+            'https://data.pro.hasura.io/v1/graphql'
+          )
+
+          echo "Payload: $REQUEST_PAYLOAD"
+          echo "Response: $RESPONSE"
+
+          # Check if the response contains errors
+          if [[ $(echo "$RESPONSE" | jq -e '.errors') != "null" ]]; then
+            echo "Error occurred: $RESPONSE"
+            exit 1
+          fi
+
       - name: Get Tenant Admin Secret
         id: get-admin-secret
         env:
