properly error check gql queries, stop uploading failure artifacts and just log them

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -116,10 +116,9 @@ jobs:
             --output list-neon-branches-response.json
       - name: Upload list branches failure
         if: failure() && steps.list-branches.outcome == 'failure'
-        uses: actions/upload-artifact@v3
-        with:
-          name: list-neon-branches-failure.json
-          path: list-neon-branches-response.json
+        run: |
+          echo "Failed to list branches"
+          cat list-neon-branches-response.json
       - name: Get main Neon branch
         id: get-main-branch
         run: |
@@ -152,10 +151,9 @@ jobs:
               }"
       - name: Upload create branch failure
         if: failure() && steps.create-branch.outcome == 'failure'
-        uses: actions/upload-artifact@v3
-        with:
-          name: create-neon-branch-failure.json
-          path: create-neon-branch-response.json
+        run: |
+          echo "Failed to create branch"
+          cat create-neon-branch-response.json
       - name: Output preview Neon branch endpoint
         id: parse-preview-branch-id
         run: |
@@ -198,26 +196,32 @@ jobs:
             }
           GQL
           )
-          REQUEST_PAYLOAD=$(cat <<-JSON
-            {
-              "query": "$(echo $QUERY | tr -d '\n')"
-            }
-          JSON
+
+          # Escape the QUERY variable using jq
+          ESCAPED_QUERY=$(echo "$QUERY" | jq -sRr @sh)
+
+          # Create the request payload
+          REQUEST_PAYLOAD=$(jq -n
+            # --arg: Assign the value of the shell variable to the corresponding variable in jq
+            --arg tenantId "$TENANT_ID"
+            # The jq program defining the structure of the output JSON object
+            '{ "query": $escapedQuery, "variables": { "tenantId": $tenantId } }'
           )
+
           RESPONSE=$(curl --silent --show-error --fail-with-body -X POST 'https://data.pro.hasura.io/v1/graphql' \
             -H 'Content-Type: application/json' \
             -H 'Authorization: pat ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}' \
             -d "$REQUEST_PAYLOAD"
           )
+
           echo "Payload: $REQUEST_PAYLOAD"
           echo "Response: $RESPONSE"
-          echo "$RESPONSE" > deleteTenantResponse.json
-      - name: Upload deleteTenant response
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: deleteTenantResponse
-          path: deleteTenantResponse.json
+
+          # Check if the response contains errors
+          if [[ $(echo "$RESPONSE" | jq -e '.errors') != "null" ]]; then
+            echo "Error occurred: $RESPONSE"
+            exit 1
+          fi
 
   create-hasura-preview-tenant:
     runs-on: ubuntu-latest
@@ -238,22 +242,31 @@ jobs:
             }
           GQL
           )
-          REQUEST_PAYLOAD=$(cat <<-JSON
-            {
-              "query": "$(echo $QUERY | tr -d '\n')"
-            }
-          JSON
+
+          # Escape the QUERY variable using jq
+          ESCAPED_QUERY=$(echo "$QUERY" | jq -sRr @sh)
+          REQUEST_PAYLOAD=$(jq -n --arg escapedQuery "$ESCAPED_QUERY" '{ "query": $escapedQuery }')
+
+          # Send the request using curl
+          RESPONSE=$(curl
+            --fail
+            --silent
+            --show-error
+            --location
+            --request POST
+            --header 'Content-Type: application/json'
+            --header 'Authorization: pat ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}'
+            --data "{\"query\":$ESCAPED_QUERY}"
           )
-          RESPONSE=$(curl --silent --show-error --fail-with-body -X POST 'https://data.pro.hasura.io/v1/graphql' \
-            -H 'Content-Type: application/json' \
-            -H 'Authorization: pat ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}' \
-            -d "$REQUEST_PAYLOAD"
-          )
-          echo "Payload: $REQUEST_PAYLOAD"
+
+          echo "Payload: $ESCAPED_QUERY"
           echo "Response: $RESPONSE"
-          TENANT_ID=$(echo "${RESPONSE}" | jq -r '.data.createTenant.id')
-          echo "$TENANT_ID" > tenant_id.txt
-          echo "tenant_id=$TENANT_ID" >> $GITHUB_OUTPUT
+
+          # Check if the response contains errors
+          if [[ $(echo "$RESPONSE" | jq -e '.errors') != "null" ]]; then
+            echo "Error occurred: $RESPONSE"
+            exit 1
+          fi
 
       - name: Upload Tenant ID
         uses: actions/upload-artifact@v3
@@ -281,33 +294,38 @@ jobs:
             }
           GQL
           )
-          REQUEST_PAYLOAD=$(cat <<-JSON
-            {
-              "query": "$(echo $QUERY | tr -d '\n')",
-              "variables": {
-                "tenantId": "${{ needs.create-hasura-preview-tenant.outputs.tenant_id }}"
-              }
-            }
-          JSON
+
+          # Escape the QUERY variable using jq
+          ESCAPED_QUERY=$(echo "$QUERY" | jq -sRr @sh)
+
+          # Create the request payload
+          REQUEST_PAYLOAD=$(jq -n
+            # --arg: Assign the value of the shell variable to the corresponding variable in jq
+            --arg tenantId "${{ needs.create-hasura-preview-tenant.outputs.tenant_id }}"
+            # The jq program defining the structure of the output JSON object
+            '{ "query": $escapedQuery, "variables": { "tenantId": $tenantId } }'
           )
+
           RESPONSE=$(curl --silent --show-error --fail-with-body -X POST 'https://data.pro.hasura.io/v1/graphql' \
             -H 'Content-Type: application/json' \
             -H 'Authorization: pat ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}' \
             -d "$REQUEST_PAYLOAD"
           )
+
           echo "Payload: $REQUEST_PAYLOAD"
           echo "Response: $RESPONSE"
+
+          # Check if the response contains errors
+          if [[ $(echo "$RESPONSE" | jq -e '.errors') != "null" ]]; then
+            echo "Error occurred: $RESPONSE"
+            exit 1
+          fi
+
           ENV_HASH=$(echo "${RESPONSE}" | jq -r '.data.getTenantEnv.hash')
           GQL_ADMIN_SECRET=$(echo "${RESPONSE}" | jq -r '.data.getTenantEnv.envVars.HASURA_GRAPHQL_ADMIN_SECRET')
           echo "env_hash=$ENV_HASH" >> $GITHUB_OUTPUT
           echo "gql_admin_secret=$GQL_ADMIN_SECRET" >> $GITHUB_OUTPUT
-      - name: Upload getTenantEnv response
-        id: uploadGetTenantEnvResponse
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: getTenantEnvResponse
-          path: getTenantEnvResponse.json
+
       - name: Update Tenant Env And Name
         id: updateTenantEnvAndName
         run: |
@@ -333,34 +351,38 @@ jobs:
             }
           GQL
           )
-          REQUEST_PAYLOAD=$(cat <<-JSON
-            {
-              "query": "$(echo $QUERY | tr -d '\n')",
-              "variables": {
-                "tenantId": "${{ needs.create-hasura-preview-tenant.outputs.tenant_id }}",
-                "tenantName": "${tenantName}",
-                "dbUrl": "${dbUrl}",
-                "currentHash": "${{ steps.getTenantEnv.outputs.env_hash }}"
-              }
-            }
-          JSON
+
+          # Escape the QUERY variable using jq
+          ESCAPED_QUERY=$(echo "$QUERY" | jq -sRr @sh)
+
+          # Create the request payload
+          REQUEST_PAYLOAD=$(jq -n
+            # --arg: Assign the value of the shell variables to the corresponding variables in jq
+            --arg tenantId "${{ needs.create-hasura-preview-tenant.outputs.tenant_id }}"
+            --arg tenantName "$tenantName"
+            --arg dbUrl "$dbUrl"
+            --arg currentHash "${{ steps.getTenantEnv.outputs.env_hash }}"
+            # The jq program defining the structure of the output JSON object
+            '{ "query": $escapedQuery, "variables": { "tenantId": $tenantId, "tenantName": $tenantName, "dbUrl": $dbUrl, "currentHash": $currentHash } }'
           )
+
+          echo "Payload: $REQUEST_PAYLOAD"
+          echo "Response: $RESPONSE"
+
           RESPONSE=$(curl --silent --show-error --fail-with-body -X POST 'https://data.pro.hasura.io/v1/graphql' \
             -H 'Content-Type: application/json' \
             -H 'Authorization: pat ${{ secrets.HASURA_CLOUD_ACCESS_TOKEN }}' \
             -d "$REQUEST_PAYLOAD"
           )
-          echo "Payload: $REQUEST_PAYLOAD"
-          echo "Response: $RESPONSE"
+
+          # Check if the response contains errors
+          if [[ $(echo "$RESPONSE" | jq -e '.errors') != "null" ]]; then
+            echo "Error occurred: $RESPONSE"
+            exit 1
+          fi
+
           ENDPOINT=$(echo "${RESPONSE}" | jq -r '.data.updateTenantName.tenant.project.endpoint')
           echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT
-      - name: Upload updateTenantEnvAndName response
-        id: uploadUpdateTenantEnvAndNameResponse
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: updateTenantEnvAndNameResponse
-          path: updateTenantEnvAndNameResponse.json
 
   deploy-hasura-preview:
     needs: [configure-hasura-preview-tenant]
